### ISSUE TITLE
意见集中

### ISSUE THREAD

**Issue by SwordYork** [exacity/deeplearningbook-chinese#1]
现阶段我们更希望，读者能跟我们讲讲哪里读不懂或者有问题，或者建设性的意见都可以在这个issue下提。
读不通的问题我们会慢慢修改，实在很耗时间，希望大家耐心等待，能看英文原版的同学就看英文原版，对你的好处更大。

我们自己也读过喷过很多翻译的书，为了以后被喷的少一点，我们顶住各方压力公开翻译版，所以大家现在请狠狠的喷，要是以后出版了就轻轻的喷。

各章节意见可以到对应的issue提。我们可能不会及时回复，但一定会考虑大家的意见。

**Comment by tttwwy** [comment]
书中有很多显示为：??的地方，搜索就可以看到，可能是引用出了问题？

**Comment by SwordYork** [comment]
@tttwwy 对的，部分章节和图片引用没有加上。因为没有跟其他人协调好。

**Comment by tankeco** [comment]
https://github.com/exacity/deeplearningbook-chinese/blob/master/Chapter12/applications.tex#L38
不通..

**Comment by SwordYork** [comment]
@tankeco @futianfan 这哥们蠢了，我好像认出学长了

**Comment by fairmiracle** [comment]
https://github.com/exacity/deeplearningbook-chinese/blob/master/Chapter2/linear_algebra.tex#L712
\Tr(后面多了一个)

https://github.com/exacity/deeplearningbook-chinese/blob/master/Chapter2/linear_algebra.tex#L719
$\MA\MB \in \SetR^{m\times m} \MB\MA \in \SetR^{n\times n}$中间最好断一下吧

Chapter2几乎所有公式后面没有标点. 后面的Chapter要好一些，不好意思我是强迫症。
另外，原作者没有提供LaTex源代码吗？这样翻译起来全部自己敲一遍还是很费力的。

**Comment by SwordYork** [comment]
@fairmiracle 非常感谢！@liber145 这哥们没很多时间校对，我们会催他。请放心，这种错误在下一版会减少很多。我们就需要强迫症和处女座！

邻域是我SB了

**Comment by liber145** [comment]
@fairmiracle 谢谢啊！我今天会给加上去的。

**Comment by yanhuibin315** [comment]
也许可以尝试一下Gitbook，读起来会比较方便？

**Comment by Buttonwood** [comment]
P 24 (34 / 545) dot product “点积“普遍打成了“点击”，可能输入错别字，请修正。谢谢！

**Comment by titicacafz** [comment]
hi，线性代数那章中，dot product好像误写成“点击”了。

**Comment by liber145** [comment]
@Buttonwood 谢谢指出！这个昨天在terminology中改正过了。我们的pdf更新会慢一些，因为图片没能放出来，所以有些tex上改了，但pdf还是那样。：）

**Comment by liber145** [comment]
@titicacafz 嗯，pdf暂时比tex有些滞后，那个在terminology中有修正了。谢谢指出来～

**Comment by SwordYork** [comment]
@yanhuibin315 目前没有这个打算，可能以后会考虑，多谢

**Comment by GageGao** [comment]
Iris在里面被翻译成虹膜，应该翻译成鸢尾花吧。

**Comment by huangpingchun** [comment]
pdf 版 第6页 第二段 “也不存在模型多少深才能被修饰为“深” “，"多么"误打为 "多少"了

**Comment by MaHongP** [comment]
第六章 p139 第二段“计算放射变换 z = W ⊤x + b，然后使用一个作用于每个元素的非线性函数 g(z)。”里面应该是“仿射”

**Comment by SwordYork** [comment]
@GageGao @exacity/translation 谁翻的，来确认一下。。

**Comment by SwordYork** [comment]
@huangpingchun 多谢，下一版更新

**Comment by SwordYork** [comment]
@MaHongP  多谢！ @KevinLee1110 认领。。

**Comment by liber145** [comment]
@GageGao 多谢指正！

**Comment by huangpingchun** [comment]
@SwordYork <也不存在模型多么深才能被[修饰]为“深”>  原文 quality 是不是在这里翻译为 ”形容“ 是不是更通顺一些

**Comment by futianfan** [comment]
@tankeco 谢谢学长，马上纠正。

**Comment by KevinLee1110** [comment]
@MaHongP 感谢指正，我马上去改正

**Comment by SwordYork** [comment]
@huangpingchun 我们会斟酌一下

**Comment by weijy026a** [comment]
Inventors 是不是应翻译为 发明家们 更合适？

**Comment by SwordYork** [comment]
@weijy026a 这个还不确定，这个语境下还需考虑，但我们会考虑你的建议

**Comment by acgtyrant** [comment]
每一位翻译者应该看看[《余光中：怎样改进英式中文？——论中文的常态与变态》](http://open.leancloud.cn/improve-chinese.html)。

随便看了几个句子：「这种方式是不可行的，基于下述几个原因：」可以改成「这办法不好，因为：」；「当我们识别一个照片中是哪一个物品的时候」可以改成「当我们识别照片属于哪一个物品时」

还有中文和英文用空格分隔会更好看，因为英文本来就不会这样写：This is a书which is good.

用「」代替 “” 更好。

**Comment by taiyun** [comment]
空格暂时不需要加，修改模板即可，xelatex处理的时候支持在中英文间加上空格。 @acgtyrant

**Comment by SwordYork** [comment]
@acgtyrant 好的，我们后续版本会改。

“噢，伙计，那真是太棒了”，我们减少这类翻译。

**Comment by taiyun** [comment]
后续都可以意译，用国人习惯的语言来重新表达，以读着流畅、意思表达清晰准确为准。

**Comment by SwordYork** [comment]
@taiyun 好的，我们就是这么打算的。还要迭代好几轮。

**Comment by SwordYork** [comment]
@exacity/translation 各位麻烦把关于自己的issue加到[acknowledgments_github.md](https://github.com/exacity/deeplearningbook-chinese/blob/master/acknowledgments_github.md)  。麻烦各位有一点泛化能力好不好，别人第1章提了建议请泛化到其他章。

**Comment by SwordYork** [comment]
@exacity/translation 我自己打脸了。自己也没有泛化。。。。刚刚才泛化好。

**Comment by Qingmu** [comment]
用winedit打开好像不好直接编译...有没有优雅的打开方式？？

**Comment by KevinLee1110** [comment]
@Qingmu windows平台下编译不是很友好（一方面CTEX包不全，不如TeXLive；另一方面WinEdit打开文件可能会出问题）...如果非要用WinEdit打开，可以在每个文件的开头加上`% !Mode:: "TeX:UTF-8"`这样一行

**Comment by SwordYork** [comment]
原来如此，@KevinLee1110 你加一哈？

**Comment by KevinLee1110** [comment]
@SwordYork @Qingmu 好的，我去弄一下，我要不要顺便弄个dlbook_cn_win.tex？因为在我这里编译dlbook_cn.tex会存在一个
> font-not-found
的错误，一直不知道怎么解决，我都是换成了Windows的字体

**Comment by KevinLee1110** [comment]
@SwordYork @Qingmu 好的，我去弄一下，我要不要顺便弄个dlbook_cn_win.tex？因为在我这里编译dlbook_cn.tex会存在一个
> font-not-found
的错误，一直不知道怎么解决，我都是换成了Windows的字体

**Comment by taiyun** [comment]
字体的事情大家不用纠结，理论上熟悉tex的都能找到需要的字体。可以不要那么多版本~

**Comment by itapty-ily** [comment]
请问可否把每一页的DRAFT去掉呢，因为习惯用高亮，划线标记，但是选中的时候总是会选中DRAFT，导致别的方法也标记到了

**Comment by SwordYork** [comment]
@itapty-ily 你可以发封邮件给我。出于版权原因，没有DRAFT的版本不能上传。

**Comment by huangpingchun** [comment]
representation learning是译为 表示学习好，还是 表征学习？

**Comment by liber145** [comment]
@huangpingchun 感觉表征学习好，学习表示特征。谢谢指出。

**Comment by liber145** [comment]
@huangpingchun 感觉表征学习好，学习表示特征。谢谢指出。

**Comment by SwordYork** [comment]
@liber145 别啊，我们都是表示，不是表征

**Comment by liber145** [comment]
@SwordYork 额，那明天看看怎么改吧。。

**Comment by huangpingchun** [comment]
字面上确实是“表示”的意思，但是感觉深“度学习主要是学习特征的重新表达”，表征更能体现这层意思。纯属一家之言😊

**Comment by SwordYork** [comment]
@huangpingchun @fairmiracle @tielei 多谢3位大哥这几天的细心指导，不知道你们有没有空完整地核对一章（现在的版本不行，大概两周以后，等我们全部核对完了，语句通顺一点之后）。比如@tielei 第9章，我们不会只让一个人核对，还有线下的同学一起核对。我会让老师在书出版的时候正式在前言中感谢你们。

**Comment by fairmiracle** [comment]
@SwordYork No problem.

**Comment by huangpingchun** [comment]
@SwordYork 刚查了查，发现在认知心理学里面就已经有了表征学习这个概念，众所周知，神经网络初期从认知神经科学那借鉴了不少概念，包括神经元，甚至神经网络的概念本身，而认识神经科学是认知心理学的一个分支，所以我觉得“表征学习”很有可能就是借鉴来的概念。引述一段百科里面的描述:“表征（representation）是信息在头脑中的呈现方式。根据信息加工的观点，当有机体对外界信息进行加工（输入、编码、转换、存储和提取等）时，这些信息是以表征的形式在头脑中出现的。表征是客观事物的反映，又是被加工的客体。“；如果把有机体理解为深度模型，不也是对外界的信息进行某种加工，这种加工意义上和有意义学习之一的表征学习概念上何其相似。

**Comment by SwordYork** [comment]
@huangpingchun  确实，我也看过这个信息。@liber145 也提议单独将`representation learning`译成`表征学习`，但私下讨论后为统一起见，我们暂且决定翻成`表示学习`，因为其他地方实在没法把`representation`翻成`表征`。我们也搜索了google scholar，`表示学习`占大多数。多谢您的建议，我们会向老师反馈一下。

**Comment by huangpingchun** [comment]
哈哈！没事，就是就事讨论一下，我仅仅是建议，最终还是你们team拿主意，还是看语境吧！

**Comment by SwordYork** [comment]
好的，大家的意见我们一定会仔细考虑！

**Comment by tielei** [comment]
@SwordYork 不知道你们进度急不急，不急的话可以给我分配一章哈

**Comment by SwordYork** [comment]
@tielei 非常不急，等我们自己校好第九章再通知你。

**Comment by tielei** [comment]
@SwordYork 好

**Comment by sunqianggg** [comment]
书中的Goodfeloow et al.(2013b)这种他举得例子怎么找得到，好像点击没反应。

**Comment by taiyun** [comment]
@sunqianggg 这个是参考文献~

**Comment by SwordYork** [comment]
@sunqianggg 在阅读模式（不是选择模式），一定能够点击。点击之后会跳到参考文献。具体哪里，我看看。最近事情微多，不好意思。

**Comment by happystarycy** [comment]
contributors们能否建一个QQ交流群，便于大家及时交流读书过程中遇到的问题（不一定是翻译问题，有可能是理解上的问题），这样可以共同提高。

**Comment by SwordYork** [comment]
@happystarycy QQ是没用了，等版本稳定以后我们建个微信群，大概到0.5版本，估计3个星期之后。

**Comment by Sen** [comment]
@SwordYork 
首先很感谢你们的翻译
我这边有一个需求。由于我眼睛不太好，所以我尽量看纸质书和kindle。不知道能否在readme中加上编译到mobi格式的方法呢？

**Comment by SwordYork** [comment]
@Sen 从源码编译的话，我觉得最好的是[pandoc](pandoc.org)，但由于使用了gls，会导致一些问题。从pdf转的话效果都不行，之后我会考虑用python转下。

**Comment by Sen** [comment]
@SwordYork 好的，谢谢了，我确实尝试了pandoc，图片确实都没有，公式的样子看起来也不太正确

**Comment by SwordYork** [comment]
@Sen 我今天稍微搞了一个[markdown](https://exacity.github.io/deeplearningbook-chinese/)的格式，这种格式好多了，转epub应该方便一点。过会我把gls映射一下。
@yanhuibin315 转到gitbook略微麻烦，我就不搞了。

**Comment by Sen** [comment]
@SwordYork 是的，有了epub，mobi也比较容易可以得到。不过有一些\begin{figure}[!htb]不知道是什么。

**Comment by taiyun** [comment]
@Sen 纸质书一定会初版的，敬请期待哈~

**Comment by SwordYork** [comment]
@Sen 我把gls也替换掉了，尽力了，细调还是比较麻烦的，\begin{figure}[!htb]图片和算法都没有改。暂时不搞了。

**Comment by Sen** [comment]
@SwordYork 谢谢了，我看看
@taiyun 好的，很期待

**Comment by endymecy** [comment]
我觉得，书中有些没有权威译法的专有名词不翻译成中文可能更好一些（或者在所有专有名词后面都加上英文标注）。因为没有权威的翻译，有时候翻译了，觉得莫名其妙无法理解，反而对理解原理有反作用。

**Comment by SwordYork** [comment]
@endymecy 关于术语的翻译会在v0.5版后进行讨论，目前基本都在gls里，所以改下也很快。

**Comment by HC-2016** [comment]
建议把Notation部分补上

**Comment by SwordYork** [comment]
@HC-2016 之前忘了，已经补好。

**Comment by SwordYork** [comment]
这个issue先关了，马上release beta版。非常感谢各位的意见！

**Comment by xu-kai-xu** [comment]
关于引言部分第11页的“深度信念网络”（我买的是17年12月第七次印刷的版本），建议改为“深度置信网络”，brief network，在概率统计的专业术语里 置信 更好点。另，非常感谢又非常佩服你们，提供这么及时的学习资料。
