### ISSUE TITLE
readme中的小问题

### ISSUE THREAD

**Issue by jzj1993** [exacity/deeplearningbook-chinese#109]
无关紧要的一个小问题。

readme中的“可以发邮件至echo c3dvcmQueW9ya0BnbWFpbC5jb20K | base64 -d”，实际在Mac中试了下没有输出正确结果。发现Mac中的参数和Linux不同，“-d”是“--debug”的含义，解码得用参数“-D”或者“--decode”。

~ base64 --help
Version DEBUG
Usage:	base64 [-dhvD] [-b num] [-i in_file] [-o out_file]
  -h, --help     display this message
  -v, --version  display version info
  -d, --debug    enables additional output to stderr
  -D, --decode   decodes input
  -b, --break    break encoded string into num character lines
  -i, --input    input file (default: "-" for stdin)
  -o, --output   output file (default: "-" for stdout)

**Comment by SwordYork** [comment]
这个之前有人提过 #21 ，想不出如何兼容Mac，就当一道障碍好了。

**Comment by jzj1993** [comment]
用Mac和Ubuntu分别试了下，用完整的参数“--decode”可以兼容
echo c3dvcmQueW9ya0BnbWFpbC5jb20K | base64 --decode

**Comment by SwordYork** [comment]
@jzj1993 666，这操作不错！

**Comment by SwordYork** [comment]
已更新，多谢！
