### ISSUE TITLE
怎么理解“无限强的先验是说一个隐藏单元的权值必须和它邻居 的权值相等,但在空间中改变”

### ISSUE THREAD

**Issue by Jinkeycode** [exacity/deeplearningbook-chinese#111]
9.4章节，第291页第三段第二句话。没理解，强先验和弱先验有没有通俗点的定义？为什么方差很小的高斯分布就是强先验，方差小就是弱先验？

**Comment by KevinLee1110** [comment]
作者在这一节的开头这样写到
>先验被认为是强或者弱取决于先验中概率密度的集中程度。 **弱先验具有较高的熵值**，例如方差很大的高斯分布。这样的先验允许数据对于参数的改变具有或多或少的自由性。 **强先验具有较低的熵值**，例如方差很小的高斯分布。这样的先验在决定参数最终取值时起着更加积极的作用。

卷积和池化相当于把参数给固定了，这样这些参数的分布是完全确定的0-1分布$P(w=constant)=1$, 这个分布的熵值为0，所以称之为无限强的先验。

**Comment by Jinkeycode** [comment]
卷积核也有用高斯核的吧，怎么理解“把参数给固定了”和“参数分布是0-1分布”？

**Comment by KevinLee1110** [comment]
1. 卷积是线性运算，高斯核不是。请参阅核函数一节以及卷积的基本概念。 2. 卷积运算在神经网络的连接表现上就是参数共享。参数共享是将参数进行绑定，所以这个权重值是确定的，在概率分布的表现上就是在这个绑定值处的概率为1，其余都为0。
