### ISSUE TITLE
关于实现代码

### ISSUE THREAD

**Issue by hjptriplebee** [exacity/deeplearningbook-chinese#117]
最近想撸这本书，可是发现缺少代码实现，请问有意向做配套代码吗？

**Comment by SwordYork** [comment]
@hjptriplebee 本来想写的，但没有足够的精力，已经7个月没更新了。https://github.com/exacity/simplified-deeplearning

**Comment by hjptriplebee** [comment]
@SwordYork 工作量确实比较大，如果有需要，我也可以帮忙~_~

**Comment by SwordYork** [comment]
@hjptriplebee 多谢，希望大家能一起写。我最快下周就能动手，欢迎提供代码。
