### ISSUE TITLE
第五章翻译错误

### ISSUE THREAD

**Issue by zhoupeng** [exacity/deeplearningbook-chinese#123]
原书第五章的170页“each region corresponds to a cell in the illustration”，对应于中文的136页
建议翻译为 “每个区域对应于图中的一个单元格”
错误有两点：1）这句话描述的对象是空间中的区域而不是样本
                      2）cell不适合直译

PS.
其中cell在计算机科学中的大多数情况都翻译为“单元或者单元格”，而不适合直译为“细胞”。
cell应该在书中不止一个地方出现，建议整体排查一下。

**Comment by zhoupeng** [comment]
https://github.com/exacity/deeplearningbook-chinese/pull/124

**Comment by SwordYork** [comment]
@liber145 我觉得有道理。

**Comment by liber145** [comment]
啊，这是很明显的误译，我们的校对工作粗糙了。多谢指正，前后我也排查下。
