### ISSUE TITLE
勘误第六章 6.1 实例 学习XOR

### ISSUE THREAD

**Issue by xyp079** [exacity/deeplearningbook-chinese#137]
第二段XOR函数的解释：当这些二进制值中恰好有一个为1时，XOR函数返回值为1. 和异或的定义是不一致的，同为0，异为1。

**Comment by SwordYork** [comment]
...哥们，两种定义是一样的，
同：0,0或者1,1    -> 0 -> 没有1或者都是1。
异：0,1或者1,0    -> 1 -> 恰好一个为1。
