### ISSUE TITLE
作者可否发布一个epub版?

### ISSUE THREAD

**Issue by fishfree** [exacity/deeplearningbook-chinese#138]
PDF版在手机上可读性不高。
是不是要求有点过分啊？只是不想看纸质书，真正利用碎片时间来学习。

**Comment by SwordYork** [comment]
@fishfree 这个其实版权问题更大，公开PDF也是我们争取来的。

**Comment by taiyun** [comment]
@fishfree 过分啊~  利用碎片时间可以看小说，但看这个利用碎片时间可能是不够的。

**Comment by fishfree** [comment]
@SwordYork 发现Adobe Reader横屏时在手机上阅读效果不错！就不用出epub啦。
@taiyun 发现还真只有在地铁上看得进去书，不分心。。。
