### ISSUE TITLE
翻译校正

### ISSUE THREAD

**Issue by potterhere** [exacity/deeplearningbook-chinese#143]
“第2部分 深度网络：现代实践”的前言部分，有的地方翻译与原文相去甚远，其他部分的尚在阅读中。

1. 
> 原文：This part of the book describes the core parametric function approximation technology that is behind nearly all modern practical applications of deep learning.
> 书中译文：本书这一部分描述参数化函数近似技术的核心，几乎所有现在实际应用的深度学习背后都用到了这一技术。

推荐翻译：本书这一部分描述的核心参数近似方法，几乎所有现代深度学习都有在使用。

2. 

> 原文：Scaling these models to large inputs such as highresolution images or long temporal sequences requires specialization.
> 书中翻译：将这些模型扩展到大输入（如高分辨率图像或长时间序列）需要专门化。

推荐翻译：将这些模型扩展到大输入，如高分辨率图像，需要特化的长时间序列。

**Comment by SwordYork** [comment]
第一句我们再考虑一下。
第二句原翻译问题不大，

> Scaling these models to large inputs such as highresolution images or long temporal sequences requires specialization.

主句应为：

> Scaling these models to large inputs requires specialization. 


以下是用来举例 large inputs 的

> such as high resolution images or long temporal sequences 

不过，specialization可能“特化”更好。

**Comment by potterhere** [comment]
第一句的原文感觉属于直译，理解起来可能没问题。
第二句的断句有需要修改的地方，“需要专门化”这个应该是修饰“长时间序列”的。

**Comment by SwordYork** [comment]
high resolution images 和 long temporal sequences 是并列的
