### ISSUE TITLE
章节20.4.4逐层预训练 中的stack的翻译

### ISSUE THREAD

**Issue by tjliupeng** [exacity/deeplearningbook-chinese#150]
20.4.4的原文有一句话“but after the stack is combined to form the DBM, the layer will have both bottom-up and top-down input.” 翻译成了“但在栈组合形成DBM后，该层将同时具有....”。

个人觉得这里这个stack是不是应该翻译成“堆叠”更合适，而不是“栈“。

**Comment by SwordYork** [comment]
原句是
“ A layer in the middle of the stack of RBMs is trained with only bottom-up input, but after the stack is combined to form the DBM, the layer will have both bottom-up and top-down input.”
翻译为，
RBM栈的中间层仅使用自底向上的输入进行训练，但在栈组合形成DBM后，该层将同时具有自底向上和自顶向下的输入。

这里的stack都翻译成了“栈”，因为是名词，而且栈本身也有“堆叠”的意思，而“堆叠”更像动词。当stack是动词时，我们用“堆叠”，如“ RBMs may be stacked (one on top of the other) to form deeper models.”。

**Comment by tjliupeng** [comment]
嗯，这么说可以解释。
