### ISSUE TITLE
MathJax失效了

### ISSUE THREAD

**Issue by yhx5768** [exacity/deeplearningbook-chinese#152]
> 'WARNING: cdn.mathjax.org has been retired. Check https://www.mathjax.org/cdn-shutting-down/ for migration tips.'

导致网页版Tex公式都失效了

新的好像是换到这里了
> https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js

**Comment by SwordYork** [comment]
> We  will implement a temporary redirect on cdn.mathjax.org to redirect users to cdnjs.

他们这么说的，我这问题不大，以后搞成本地的。

**Comment by yhx5768** [comment]
@SwordYork 好的吧，网页版看着还是挺方便的，等他们修复吧
