### ISSUE TITLE
勘误，4.3节基于梯度的优化方法，P77

### ISSUE THREAD

**Issue by ThroneNeNe** [exacity/deeplearningbook-chinese#176]
原文“ f的导数是包含所有偏导数的向量”，应改为“ f的梯度是包含所有偏导数的向量”

**Comment by SwordYork** [comment]
@ThroneNeNe [这里](https://github.com/exacity/deeplearningbook-chinese/blob/master/Chapter4/numerical_computation.tex#L169)已经改正，我们的PDF没更新（应该不会更新了）。见这个[commit](https://github.com/exacity/deeplearningbook-chinese/commit/98daf6b9c2adb9e69e5b62693fad2bb321e703ed#diff-bd435ace16a5f8d47cdc18aafe99ac92)更正。
