### ISSUE TITLE
勘误：第一章 “诉诸于”

### ISSUE THREAD

**Issue by Cuiyn** [exacity/deeplearningbook-chinese#179]
对应deeplearningbook-chinese/Chapter1/introduction.tex文件第329行：

> 它诉诸于学习\emph{多层次组合}这一更普遍的原理，这一原理也可以应用于那些并非受神经科学启发的\gls{ML}框架。

因为高中时候做了不少修改病句的练习，感觉这里“诉诸于”有些奇怪。“诸”这里的用法来自于古汉语，意为“之于”，例句有《愚公移山》中的“投诸渤海之尾”。

因为“诸”意为“之于”，已经有“于”一字，所以第一章这里的“诉诸于”犯了语意重复的错误，应删去“于”，改为“诉诸”或“诉之于”即可。现代汉语还可以参考的用法有“诉诸权威”、“诉诸法律”等，都是不应该有“于”字的。

另对各位的辛勤劳动表示敬佩与感谢！

**Comment by SwordYork** [comment]
@Cuiyn 很有道理，多谢
