### ISSUE TITLE
勘误：10.2.1 Teacher forcing is a procedure that emerges from the maximum likelihood criterion

### ISSUE THREAD

**Issue by voidguy** [exacity/deeplearningbook-chinese#180]
“Teacher forcing is a procedure that emerges from the maximum likelihood criterion, in which during training the model receives the ground truth output y(t) as input at time t+ 1” 被翻译为“训练模型时，导师驱动过程不再使用最大似然准则，而在时刻$t+1$接收真实值$y^{(t)}$作为输入”，应该翻译错了，不论是emerges from的本来意思，还是结合上下文，原作者的意思应该是“导师驱动是一个源自于最大似然准则的过程，在时刻t+1接受真实值y(t)作为输入”

**Comment by SwordYork** [comment]
@voidguy 恩，我看错了，多谢
