### ISSUE TITLE
请问能再发一版新版的pdf吗，已经一年多没更新了

### ISSUE THREAD

**Issue by markcheney1** [exacity/deeplearningbook-chinese#196]
请问能再发一版新版的pdf吗，已经一年多没更新了

**Comment by markcheney1** [comment]
请问能再发一版新版的pdf吗，已经一年多没更新了

**Comment by mathcad** [comment]
这本书已经发行纸质版了，受到版权方要求，作者不会再更新pdf电子书了。你可以用源码自行编译pdf

**Comment by markcheney1** [comment]
> 这本书已经发行纸质版了，受到版权方要求，作者不会再更新pdf电子书了。你可以用源码自行编译pdf

恩 主要用源码编译是没有图片的

**Comment by markcheney1** [comment]
如果有电子书的话，想去买一本
