### ISSUE TITLE
勘误 10.2.3

### ISSUE THREAD

**Issue by hccc18** [exacity/deeplearningbook-chinese#201]
原文：

> In this case, the outputs y are conditionally independent given the sequence of x values.

翻译：

> 在这种情况下，输出$\Vy$与给定的$\Vx$序列是条件独立的。 

建议：
在这种情况下，给定x序列后，输出的y值间条件独立。

**Comment by futianfan** [comment]
这个确实翻译有误。谢谢

**Comment by hccc18** [comment]
> 这个确实翻译有误。谢谢

不客气！谢谢你们辛苦翻译。
