### ISSUE TITLE
10.11.1    倒数第四段 关于   heuristic deviation  的翻译

### ISSUE THREAD

**Issue by liguge** [exacity/deeplearningbook-chinese#226]
查阅了一些资料    heuristic deviation大部分都翻译为【启发式偏差】，而不是【启发式偏置】，用后者搜索baidu的时候  搜到的东西根本不是自己想要的   前者还可以。

**Comment by wxq0910** [comment]
您好，邮件已收到。我将尽快给您回复！

**Comment by xy-always** [comment]
已经收到您的邮件。

**Comment by Xl-wj** [comment]
您好，信件已经收到。王健。

**Comment by 1023620580** [comment]
收到，若无回复，请打电话联系通知。
