### ISSUE TITLE
第5.8节主成分出错求助

### ISSUE THREAD

**Issue by kate-chen** [exacity/deeplearningbook-chinese#229]
![image](https://user-images.githubusercontent.com/32677777/105841408-7e9e1f80-600f-11eb-9321-a3516f4f9032.png)
此处的图下说明，z等于x的转置乘于W
![image](https://user-images.githubusercontent.com/32677777/105841693-fc622b00-600f-11eb-91b8-1f64e520aaec.png)
但是这里又变成z等于=w的转置乘于x
![image](https://user-images.githubusercontent.com/32677777/105841844-42b78a00-6010-11eb-91ce-e2f4ca3c952d.png)
到了这地方又是
Z=XW
这三处z到底哪里出错

**Comment by peng-shao** [comment]
都没大错，如果非要说有小瑕疵的话，那就是第一处的z如果写成z’可能会歧义更小，因为一般来说，向量都是列向量而不是行向量。至于大写的X和Z作为矩阵，是由这些向量转置成**行**后堆叠起来的，即X'=(x_1, x_2, \dots, x_n), Z'=(z_1, z_2, \dots, z_n)。所以W'X'=(W'x_1,W'x_2,\dots, W'x_n)=(z_1, z_2, \dots, z_n)=Z'，即Z=XW

**Comment by kate-chen** [comment]
明白了，谢谢
