### ISSUE TITLE
版本dlbook_cn_v0.1.1-alpha问题

### ISSUE THREAD

**Issue by tonyzeng2016** [exacity/deeplearningbook-chinese#23]
版本dlbook_cn_v0.1.1-alpha.pdf第1页到第39页都为空白,谢谢.

**Comment by SwordYork** [comment]
我等等再传一版，我们这没有问题，你用啥PDF阅读器？在浏览器里打开试试？

**Comment by tonyzeng2016** [comment]
ubuntu 14.04 下的文档查看器 3.10.3. 在浏览器没法试.

**Comment by KevinLee1110** [comment]
@tonyzeng2016 可以拖进Chrome里试一下

**Comment by tonyzeng2016** [comment]
@KevinLee1110 ubuntu上拖到chrome中就是下载操作,试不了;

**Comment by SwordYork** [comment]
@tonyzeng2016  更新了一版，再看看。估计你的chrome没装PDF插件，是chromium吧。服了ubuntu。
