### ISSUE TITLE
Chapter 8 the translation here misleading the improper meaning

### ISSUE THREAD

**Issue by Wenhua-Hu** [exacity/deeplearningbook-chinese#238]
你好,

![image](https://user-images.githubusercontent.com/13209864/175279489-47509746-8730-464b-9574-00c895c8cb54.png)
原文里面时表示某些干扰不是特指噪声干扰. 例外 a 表示某一个过去时间 t，当前时间t到测量时间a间隔应该是 t-a .

胡文华

**Comment by Sudouble** [comment]
来件已收到，我会尽快处理！

**Comment by wxq0910** [comment]
您好，邮件已收到。我将尽快给您回复！

**Comment by Xl-wj** [comment]
您好，信件已经收到。王健。

**Comment by 1023620580** [comment]
收到，若无回复，请打电话联系通知。

**Comment by waboo258** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复.祝你假期快乐。

**Comment by KevinLee1110** [comment]
你好，首先，这是第九章的翻译内容，不是标题里的第8章，参考[Sec 9.1](https://www.deeplearningbook.org/contents/convnets.html)，请先阅读原文。原文"Now suppose that our laser sensor is somewhat noisy."可以翻译成传感器存在噪声，目前的翻法应该不会引起歧义。

其次，请注意这里`a`的使用，这里`a`第一次出现是用来解释`w(a)`这个函数的，而且原文是"a is the age of a measurement"，所以翻译成时间间隔没有问题，跟下文没有关系。注意，公式9.1中的`a`是时刻，`w(t-a)`中的`t-a`是时间间隔。原文这里写的容易混淆。

**Comment by Wenhua-Hu** [comment]
谢谢

**Comment by Xl-wj** [comment]
您好，信件已经收到。王健。

**Comment by wxq0910** [comment]
您好，邮件已收到。我将尽快给您回复！

**Comment by 1023620580** [comment]
收到，若无回复，请打电话联系通知。

**Comment by waboo258** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复.祝你假期快乐。
