### ISSUE TITLE
Deep Learning for Software Engineers?

### ISSUE THREAD

**Issue by ZuzooVn** [exacity/deeplearningbook-chinese#26]
Thanks for your translation version.
Currently, I am making: Machine Learning for Software Engineers (https://github.com/ZuzooVn/machine-learning-for-software-engineers)

Did you have any suggestion for Deep Learning's Top-down learning path for Software Engineers ?

Thank you

**Comment by SwordYork** [comment]
Thanks for your great work! [Machine Learning for Software Engineers](https://github.com/ZuzooVn/machine-learning-for-software-engineers) is extremely useful (not only useful for software engineers but also for others).
If a software engineer has finished the Machine Learning path, it would be easier to learn Deep Learning. 
As for a top-down learning path, I think one should follow these steps:
1. Find the popular works on github, like [TopDeepLearning](https://github.com/aymericdamien/TopDeepLearning).
2. Run some interesting code, like [neural-style](https://github.com/jcjohnson/neural-style).
3. Go deeper and deeper into some projects, like [Keras](https://github.com/fchollet/keras). It is much easier for software engineers.
4. Read some relative papers and reimplement some codes, like [GAN](https://github.com/openai/improved-gan).

But that's just my view, and my suggestion. I'm not an expert, thus I don't know how to become an expert.

**Comment by ZuzooVn** [comment]
I found another great resource:

Open Source Deep Learning Curriculum: http://www.deeplearningweekly.com/pages/open_source_deep_learning_curriculum

**Comment by SwordYork** [comment]
This resource is very detailed, and overlapped with Machine Learning.
I think [cs231n](http://cs231n.stanford.edu/) or [cs224d](http://cs224d.stanford.edu/)  is a good starting, and [Roadmap](https://github.com/songrotek/Deep-Learning-Papers-Reading-Roadmap) may be the academic front.
