### ISSUE TITLE
base64 解码的问题

### ISSUE THREAD

**Issue by kxxoling** [exacity/deeplearningbook-chinese#29]
README 里留的邮箱是 `echo c3dvcmQueW9ya0BnbWFpbC5jb20K | base64 -d`，但是我正在使用的 Ubuntu 和 macOS 自带的 base64 行为并不一致，macOS 下需要改为 `base64 -D`，要不要注明一下？

**Comment by SwordYork** [comment]
你好，这个不想管了，就这样好了，知道是base64编码的就行。Tuck mac !
