### ISSUE TITLE
参考文献的真实页码和目录中的页码并不对应

### ISSUE THREAD

**Issue by 9578577** [exacity/deeplearningbook-chinese#35]
参考文献的真实页码和目录中的页码并不对应
正文中是590页
目录中是578页

**Comment by SwordYork** [comment]
@9578577 我也发现了，但我不知道怎么回事。

**Comment by 9578577** [comment]
尝试对书进行编译，但发现参考文献文件为空，因此无法进一步调试。
初步感觉是参考文献加入目录时放置的位置不对。
但是不好更改。
建议使用 package tocbibind解决这个问题

**Comment by 9578577** [comment]
补充一下，tocbibind可以这样写
\usepackage[chapter, nottoc, notlot, notlof]{tocbibind}
将章加入，但是不加入目录、表目录和图目录。
此时，参考文献需要用章标识。

**Comment by SwordYork** [comment]
@9578577 不好意思，bib文件不能公开（原作者给的）。
目录页码和术语页码不对的问题都应该是由同一个原因引起的，\usepackage[chapter, nottoc, notlot, notlof]{tocbibind} 也不行，估计跟chapter的cleardoublepage有关，没有搞定，以后再试。

**Comment by 9578577** [comment]
大家好：
呃，bib文件没有关系。
总得来说，我对文档的调整如下：

调整tocbibind为\usepackage[chapter, nottoc, notlot, notlof]{tocbibind} 

对于感谢，在对应tex文件中添加\chapter{感谢}

对于符号注释，在对应文件中添加\chapter{符号注释}

添加\frontmatter在\begin{document}之后

添加\backmatter在\appendix之前




经过上述调整，书的效果见附件。我用的环境为Texlive2016.

--------------------------------------------------------------------------------
--------------------    参考文献的目录页码与正文页码  ----------------------
--------------------------------------------------------------------------------


上图为参考文献正文页码，章节开始之前是396，所以章节所在页面为397.




------------------
          谢谢！


康俊民电话：15902956283


 




------------------ 原始邮件 ------------------
发件人: "Nouce";<notifications@github.com>;
发送时间: 2017年1月12日(星期四) 中午12:03
收件人: "exacity/deeplearningbook-chinese"<deeplearningbook-chinese@noreply.github.com>; 
抄送: "飞翔的小兔"<9578577@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [exacity/deeplearningbook-chinese] 参考文献的真实页码和目录中的页码并不对应 (#35)




@9578577 不好意思，bib文件不能公开（原作者给的）。
 目录页码和术语页码不对的问题都应该是由同一个原因引起的，\usepackage[chapter, nottoc, notlot, notlof]{tocbibind} 也不行，估计跟chapter的cleardoublepage有关，没有搞定，以后再试。

**Comment by 9578577** [comment]
大家好：
呃，bib文件没有关系。
总得来说，我对文档的调整如下：
[dlbook_cn.pdf](https://github.com/exacity/deeplearningbook-chinese/files/700707/dlbook_cn.pdf)

1. 调整tocbibind为\usepackage[chapter, nottoc, notlot, notlof]{tocbibind} 
2. 对于感谢，在对应tex文件中添加\chapter{感谢}
3. 对于符号注释，在对应文件中添加\chapter{符号注释}
4. 添加\frontmatter在\begin{document}之后
5. 添加\backmatter在\appendix之前

经过上述调整，书的效果见附件。我用的环境为Texlive2016.

**Comment by SwordYork** [comment]
@9578577 多谢，我发现不是\usepackage[chapter, nottoc, notlot, notlof]{tocbibind}的问题，是编译问题。
在插入bib后没有再次更新编译，导致公开的PDF页码不对，现在好了，具体见[release](https://github.com/exacity/deeplearningbook-chinese/releases/edit/v0.4-alpha)。
多谢！

**Comment by jnulzl** [comment]
你们编译用的是啥环境啊？？？我用texLive2016(Windows)老是出错。

**Comment by jnulzl** [comment]
都很好，就是没有bib和figure。

**Comment by SwordYork** [comment]
@jnulzl 也就是能编译了？一般编译不过都是因为字体问题。图片和bib由于版权我们不能上传。不好意思。

**Comment by jnulzl** [comment]
恩，下载了Adobe相关字体编译通过。不过bib和figure可以根据英文网页版自己搞定，只是工作了有点大而已，谢谢了。

**Comment by 9578577** [comment]
网页版也不好弄吧，图片下不来

**Comment by SwordYork** [comment]
@9578577 @jnulzl 确实很麻烦，只能从pdf里面截取。好几百张图，工作量还是很大的。最好的方法是自己编译中文版去掉水印后，对照着英文版看。

**Comment by SwordYork** [comment]
这个问题已经ok，剩下排版问题最后细化。
