### ISSUE TITLE
第一章的建议

### ISSUE THREAD

**Issue by NeutronT** [exacity/deeplearningbook-chinese#37]
“20世纪40年代到60年代深度学习的雏形出现在控制论中，20世纪80年代到90年代深度学习以联结主义为代表，并于2006年开始，以深度学习之名复兴。”建议再做更改：20世纪40年代到60年代，深度学习的萌芽出现在控制论中，80年代到90年代的深度学习表现为联结主义，直到2006年，才真正以深度学习之名复兴。
13页，“理解大脑和人类智力背后的原则也非常有趣”，建议译为“理解大脑和人类智能背后的原理也非常有趣”。
13-14页，“机器学习框架且不必是受神经启发的”，建议译为“机器学习框架且不必是受神经系统启发的”
14页的“自适应线性元件(adaptive linear element, ADALINE)”，建议译为“自适应线性单元”，目前国内很多书都是这么叫的。

**Comment by SwordYork** [comment]
多谢，收到，翻译得很好。如果您有时间，在 https://via.hypothes.is/https://exacity.github.io/deeplearningbook-chinese/Chapter1_introduction/ 批注更快捷。

**Comment by NeutronT** [comment]
适拜读诸位大作，略有陋见，见笑！后续将继续体会诸位艰辛，望能锦上添花，将不胜荣幸！

**Comment by SwordYork** [comment]
@NeutronT 非常感谢，您的建议非常到位！ 在大家的建议下，第一章已经更新很多，详见 https://github.com/exacity/deeplearningbook-chinese/raw/master/Chapter1/dlbook_cn_chapter1.pdf
