### ISSUE TITLE
图片无法加载

### ISSUE THREAD

**Issue by imageslr** [exacity/deeplearningbook-chinese#38]
章节中图片内容显示的都是如下的代码段：
\begin{figure}[!htb]
\ifOpenSource
\centerline{\includegraphics{figure.pdf}}
\else
\centerline{\includegraphics{Chapter1/figures/polar_color}}
\fi
\caption{不同表示的例子：假设我们想在散点图中画一条线来分隔两类数据。
在左图，我们使用笛卡尔坐标表示数据，这个任务是不可能的。 
右图中，我们用极坐标表示数据，可以用垂直线简单地解决这个任务。（与David Warde-Farley合作画出此图。）}
\end{figure}
 

链接也无法显示，而是只显示：
{cite?}

请问这是为什么？

**Comment by SwordYork** [comment]
不好意思，由于版权问题，不能放出图片。你可以下载PDF查看图片。引用也是因为版权问题。
网页主要是校对批注用途，不用于阅读。
