### ISSUE TITLE
发现了个笔误, 已经创建pull request

### ISSUE THREAD

**Issue by zhangyafeikimi** [exacity/deeplearningbook-chinese#40]
#39

**Comment by liber145** [comment]
@zhangyafeikimi 多谢指正！现已修正。Issue中有设立各个章节，还请校对建议放在那里，会比较方便统一修正。另外，不知道你有没有时间帮忙校对一章，若有兴趣，请参看[校对认领](https://github.com/exacity/deeplearningbook-chinese#校对认领)。

**Comment by zhangyafeikimi** [comment]
可以认领4 8 17的简单阅读

**Comment by SwordYork** [comment]
@zhangyafeikimi 你好，我们已经合并你的建议，多谢！
