### ISSUE TITLE
两个小错误

### ISSUE THREAD

**Issue by kangqf** [exacity/deeplearningbook-chinese#41]
deeplearningbook-chinese/Chapter8/optimization_for_training_deep_models.tex
lines 392 
由于\firstgls{model_identifiability}问题，\gls{NN}和任意具有多个等效参数化\gls{latent_variable}的模型都会具有多个\gls{loccal_minima}。

最后一个应该是　\gls{local_minima}

另外，我就找到了 `Adobe Song Std L` Light格式的字体，没有找到`Adobe Song Std` 格式的字体，所以
deeplearningbook-chinese/dlbook_cn.tex 中的 lines 6 \setCJKmainfont[AutoFakeBold=true]{Adobe Song Std}
要改成\setCJKmainfont[AutoFakeBold=true]{Adobe Song Std L}才能编译通过

**Comment by kangqf** [comment]
另外，想问问，如果不公开bib文件，有没有什么方法可以让编译后引用处的问号去掉呢？实在有点丑 ):

**Comment by SwordYork** [comment]
@kangqf 收到，多谢！字体问题先不管。line 392 应该是最近引入的错误，@futianfan 先看看，之后校正。

可以去掉cite，如下可以去掉第一章的cite
`sed -i 's/\\cite[^}]*}//g' Chapter1/introduction.tex`
或者如下可以全部去掉
`find . -name \*tex -exec sed -i 's/\\cite[^}]*}//g' {} \; `

也可以重定义cite。

**Comment by kangqf** [comment]
嗯嗯，还有一个小问题，就是我自行编译后的书签（不是目录）没有·release·的·pdf·漂亮，就是书签只有一个题目，没有章节的提示，比如3.1小节的 `3.1` 的提示。

**Comment by SwordYork** [comment]
有道理，我发现是因为用于编译release的tex和上传的tex不一致，等等修改一下。
