### ISSUE TITLE
5.1.4 实例：线性回归

### ISSUE THREAD

**Issue by yaoxiuyong** [exacity/deeplearningbook-chinese#44]
参数是控制系统行为的值。 在这种情况下，wiwi是系数，会和特征 xixi相乘之后全部相加起来。 我们可以将ww看作是一组决定每个特征如何影响预测的权重。 如果特征 xixi对应的权重wiwi是正的，那么特征的值增加，我们的预测值y^y^也会增加。#  _`如果特征 xixi对应的权重wiwi是负的，那么特征的值减少，我们的预测值y^y^也会减少。`_ 如果特征权重的大小很大，那么它对预测有很大的影响；如果特征权重的大小是零，那么它对预测没有影响。

错误点：#  _`如果特征 xixi对应的权重wiwi是负的，那么特征的值减少，我们的预测值y^y^也会减少。
错误原因：如果系数为负，那么应该是特征的值增加，我们的预测值会减少；

**Comment by SwordYork** [comment]
很有道理，原文也是这么写的。多谢！ @liber145

**Comment by liber145** [comment]
@yaoxiuyong @SwordYork 嗯，你说得是对的，多谢帮忙校对！现修改为
“如果特征xixi对应的权重wiwi是负的，那么特征的值增加，我们的预测值y^y^会减少。”
