### ISSUE TITLE
有替换采样-->有放回采样 (7.22 Dripout     page: 221) 

### ISSUE THREAD

**Issue by zhouqingping** [exacity/deeplearningbook-chinese#45]
从训练集  **有替换采样**  构造k 个不同的数据集，然后在训练集i 上训练模型i

这儿表达的是采样时样本可重复，**有替换采样**有这个意思。但是概率统计的常规说法是**有放回采样**。

建议把  **有替换采样** 改为 **有放回采样**
（google上搜索，前一种说法基本没有，后一种还是很多的）

**Comment by SwordYork** [comment]
有道理，多谢！

**Comment by SwordYork** [comment]
已更正，多谢！
