### ISSUE TITLE
我用TeXwork在window下无法编译通过

### ISSUE THREAD

**Issue by dennybai** [exacity/deeplearningbook-chinese#46]
请问你们是用什么软件编译的？

**Comment by SwordYork** [comment]
应该是字体问题，我们xelatex编译的。

**Comment by dennybai** [comment]
我也用xelatex 编译, 没有编译过去。 请问这本书编译的时候， 用的是什么字体? 我装过一些字体，但 并没有覆盖上。

**Comment by SwordYork** [comment]
[主文件](https://github.com/exacity/deeplearningbook-chinese/blob/master/dlbook_cn.tex) 是Adobe的字体，你可以添加看看。或者把错误贴上来看看。

**Comment by dennybai** [comment]
我电脑win7， 装有 adobe的(仿宋、楷体、黑体、宋体) ， 错误提示是"! Undefined control sequence.
l.3 \chapter
            {前言}
? "

**Comment by SwordYork** [comment]
那我不清楚了，我没在win下试过。

**Comment by KevinLee1110** [comment]
@dennybai 这种错误提示我们也找不出具体的错误原因... TeXworks一般很少有人会**单独**使用这款软件吧，我猜测你可能用的是CTEX或者TeXLive？如果是CTEX，因为宏包不全确实编译不过；TeXLive貌似没问题。我是在Windows 10下编译的，用的TeXLive 15，安装字体后，编译没问题。

**Comment by dennybai** [comment]
谢谢。我装一个TexLive，试试看

**Comment by NBZCC** [comment]
如果不用MAKEFILE编译可以试试在开头加一行 %!Tex Program = xelatex 不过工程里没有bib 会有很多'?'

**Comment by whyscience** [comment]
试了半天 最新的texlive+windows10确实可以

**Comment by freedomRen** [comment]
没有图也能编译通过？？

**Comment by SwordYork** [comment]
@freedomRen 我们做了处理，有个替代图。

**Comment by Nghingtim** [comment]
@dennybai 我在win10的CTex编译下，也遇到类似的问题。请问你解决了吗？

**Comment by xuanqqq** [comment]
我在编译时出现了问号，应该咋解决

**Comment by Sudouble** [comment]
来件已收到，我会尽快处理！

**Comment by wxq0910** [comment]
您好，邮件已收到。我将尽快给您回复！

**Comment by xy-always** [comment]
已经收到您的邮件。

**Comment by waboo258** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复.祝你假期快乐。

**Comment by Xl-wj** [comment]
您好，信件已经收到。王健。

**Comment by 1023620580** [comment]
收到，若无回复，请打电话联系通知。
