### ISSUE TITLE
Chap7 早停止部分翻译错误

### ISSUE THREAD

**Issue by friskit-china** [exacity/deeplearningbook-chinese#47]
https://github.com/exacity/deeplearningbook-chinese/blob/master/Chapter7/regularization.tex#L778

原文：
then L2 regularization and early stopping ......

译文：
那么L2正则项和权重衰减 ......

应该是早停止，翻译成了权重衰减。

：）

**Comment by SwordYork** [comment]
收到！多谢，火眼金睛！
