### ISSUE TITLE
好多流程和公式类的latex表达式显示不出来

### ISSUE THREAD

**Issue by ystyle** [exacity/deeplearningbook-chinese#48]
好多流程和公式类的latex表达式显示不出来, f12看network 全部都加载成功了啊 . 
还有向量, 矩阵这种显示样式不对

**Comment by SwordYork** [comment]
你是说网页吗，正常现象，可以看pdf。网页仅供搜索用。

**Comment by ystyle** [comment]
原来还有pdf
