### ISSUE TITLE
请问这里翻译的中文版计划要出版了吗？

### ISSUE THREAD

**Issue by meshiguge** [exacity/deeplearningbook-chinese#49]

**Comment by SwordYork** [comment]
出版社已经拿去排版了，他们会尽快。

**Comment by acbetter** [comment]
等纸质版等得我好辛苦～出版社加油！

**Comment by huyizheng** [comment]
是由哪家出版社出版呢？

**Comment by SwordYork** [comment]
@huyizheng 不好意思，出版社不让我们在GitHub上说，怕MIT出版社找他们麻烦。

**Comment by meshiguge** [comment]
> Can I translate the book into Chinese?
> Posts and Telecom Press has purchased the rights.

这是作者自己说的啊。。。

**Comment by SwordYork** [comment]
@meshiguge 确实，但我们不能提，尴尬。。

**Comment by luke12321** [comment]
大概什么时候能购买呢？出来后我报个名购买，哪里能看到购买通知呢？

**Comment by SwordYork** [comment]
@luke12321 看出版社进度了，估计还要2个月左右。。应该微博会有通知。
