### ISSUE TITLE
7.1 公式错误

### ISSUE THREAD

**Issue by wizyoung** [exacity/deeplearningbook-chinese#52]
**7.1 参数范数惩罚** 部分公式7.6错误，最后少乘了一个(w-w*)

**Comment by NBZCC** [comment]
\hat J(\Vtheta) = J(\Vw^*) + \frac{1}{2}(\Vw - \Vw^*)^\top \MH (\Vw - \Vw^*),
最后乘了(w-w*) 并没有问题

**Comment by wizyoung** [comment]
奥，抱歉，我看成最后那个括号里面是H的参数了。确实没错。。

**Comment by NBZCC** [comment]
H在这里单纯是一个数值矩阵而不是函数矩阵 加油

**Comment by SwordYork** [comment]
多谢各位！看得那么仔细！
