### ISSUE TITLE
Ch3 一处翻译

### ISSUE THREAD

**Issue by sailordiary** [exacity/deeplearningbook-chinese#53]
**Line 606.** 这个公式是以**Reverend Thomas Bayes**来命名的，他是第一个发现这个公式特例的人。
贝叶斯(Thomas Bayes)是英格兰长老会牧师(reverend)，"Reverend"不是他名字的一部分。

**Comment by SwordYork** [comment]
[ the Reverend Thomas Bayes](https://bayesian.org/bayes) 这里我不知道为什么大写Reverend，不清楚英语文化，但原书是大写（the Reverend Thomas Bayes），所以我觉得这里不能翻成牧师。不知道其他人意见如何。 @exacity/translation

**Comment by sailordiary** [comment]
社会上的职位或专业上的头衔都要大写，比如Professor、President、Reverend、Father、Bishop...
[英文维基](https://en.wikipedia.org/wiki/Bayes%27_theorem) 也有出现：

> Bayes' theorem was named after the **Reverend** Thomas Bayes (1701–1761), who studied how to compute a distribution for the probability parameter of a binomial distribution (in modern terminology).

**Comment by SwordYork** [comment]
原来如此，再看看其他人意见。

**Comment by taiyun** [comment]
翻译成牧师没问题，他的确是哈~

**Comment by liber145** [comment]
嗯，赞成译成牧师

**Comment by KevinLee1110** [comment]
嗯，我也觉得翻译成牧师没问题，Reverend确实不是他名字的一部分。
