### ISSUE TITLE
第七章中英阅读 修改建议

### ISSUE THREAD

**Issue by NBZCC** [exacity/deeplearningbook-chinese#55]
[proofread.txt](https://github.com/exacity/deeplearningbook-chinese/files/907365/proofread.txt)
1个！表示可能需要修改
2个！！表示有问题需要修改，也可能是我看错或者理解由问题
3个！！！表示问题比较严重一定要改，如果觉得原译文是对的请和我讨论
没有！表示只是个人阅读习惯

修改得比较激进 这样似乎更有可能跳出局部最优hahaha

**Comment by SwordYork** [comment]
@NBZCC 非常感谢，之后我会合并！有问题，我再与你讨论。

**Comment by SwordYork** [comment]
@NBZCC 非常非常感谢，基本上你的每一条都很有用。出版社也给了反馈，我们这两天给他们修订。能否告知姓名，以表示感谢（不方便的话，可以发我邮箱sword.york@gmail.com）。

**Comment by SwordYork** [comment]
先关了issue，因为我们要整合一波了。多谢！
