### ISSUE TITLE
请教6.4章 两个函数的推导

### ISSUE THREAD

**Issue by ninesunqian** [exacity/deeplearningbook-chinese#57]
A：有这么一段“这在二进制情况下很容易看到：向量v∈{0,1}^n上的可能的二进制函数的数量是2^(2^n)，并且选择一个这样的函数需要2^n位，这通常需要O(2^n)的自由度。”   请问二进制函数的数量，以及选择一个这样的函数需要2^n位，是如何计算出来的

B：公式 6.42的推导。

谢谢！

**Comment by KevinLee1110** [comment]
@ninesunqian v是一个n维的向量，每一维都可以取0或1，因此有`2^n`种可能的取值。二进制函数是把v映射到0或1，所以这样的二进制函数一共有`2^{2^n}`个。后面我是这样理解的：我们考虑构建一个2层的神经网络来实现其中一个函数。每个隐含单元处理一种输入，例如最上面的隐含单元处理输入为000...0(n个0)的输入，那么这样的隐含单元一共需要`2^n`个。这里与前面的说法："可能每个隐含单元对应着一个不同的输入"相呼应。

公式6.42我没有推过，可以参考[这篇文章](https://arxiv.org/abs/1402.1869)的Corollary 5。等我忙完这一阵再仔细读一下这篇文章...

**Comment by ninesunqian** [comment]
我把“二进制函数”理解错了，谢谢KevinLee1110

**Comment by KevinLee1110** [comment]
这里我可能翻译成"二进制"不是特别好，翻译成"二值函数"更容易理解一些。我去修改一下。
