### ISSUE TITLE
8.3节中研究算法收敛率时，提到了额外误差和泛化误差，这两个有关联吗？

### ISSUE THREAD

**Issue by ninesunqian** [exacity/deeplearningbook-chinese#59]
8.3 中有这么一句“研究优化算法的收敛率，一般会衡量额外误差 J(θ)−minθ，即当前代价函数超出最低可能代价的量。 SGD应用于凸问题时，k步迭代后的额外误差量级是O(1/k√)，在强凸情况下是O(1k)。 除非假定额外的条件，否则这些界限不能进一步改进。 批量梯度下降在理论上比随机梯度下降有更好的收敛率。 然而，Cram'er-Rao界限~{cite?}指出，泛化误差的下降速度不会快于O(1/k)”

泛化误差的下降速度，是否也是按照额外误差计算的？ 另外额外误差是针对训练集还是针对测试集，抑或是纯理论计算出来的？

**Comment by SwordYork** [comment]
你好，都是理论计算，excess error关于优化，跟泛化无关。泛化误差的理论我没接触过。 @liber145

**Comment by liber145** [comment]
@ninesunqian 具体地计算泛化误差的值一般是在测试集上进行估计的。讨论泛化误差的下降速度时也是用额外误差的方式计算的。 额外误差是指 当前迭代情况下的代价 J(theta_k)  和  最低代价 J(theta_*)  之间的差距。如果 J 是凸的，那么额外误差会以一定速率慢慢趋向于0。额外误差可用于理论分析研究收敛率，也可以计算训练集和测试集上的额外误差，观察是否满足理论结果。因此，这两个误差也算是有关联吧，一个衡量与最小误差之间的距离，一个衡量未知数据上的误差。：）

**Comment by ninesunqian** [comment]
明白了，谢谢 @liber145  和 @SwordYork
