### ISSUE TITLE
PDF 是否可以去掉水印

### ISSUE THREAD

**Issue by logicxin** [exacity/deeplearningbook-chinese#61]
感谢deeplearningbook-chinese的翻译团队，翻译质量很好。 但是在看PDF版本的时候， 由于水印太大，文章经常没法标注。那是否可以去掉或者将水印变小呢，可以提高阅读体验~

**Comment by SwordYork** [comment]
你好，谢谢！不能去掉水印，有版权问题。你可以自行编译，但没有图片，影响也不大。

**Comment by Coder-Yu** [comment]
可以用acrobat去掉，不过得一页页删除中间那个大水印

**Comment by SwordYork** [comment]
@Coder-Yu 哥们别搞事。。。自己知道就行

**Comment by Coder-Yu** [comment]
绝不外传，我懂的 ^_^

**Comment by freedomRen** [comment]
acrobat 应该有批量水印去除插件，不过这个好久没有使用过了。遇到难懂的还是对照看看英文原版吧。
