### ISSUE TITLE
关于版权问题

### ISSUE THREAD

**Issue by Lyken17** [exacity/deeplearningbook-chinese#62]
你好，译者

在原书主页的FAQ中，我注意到作者有申明

> Can I translate the book into Chinese?
> Posts and Telecom Press has purchased the rights.

给本项目提供稿费的是Posts／Telecom Press 吗？

**Comment by taiyun** [comment]
是啊。

**Comment by Lyken17** [comment]
那可以安心贡献了.   之前早有翻译打算，但看到这个FAQ就一直没动手
