### ISSUE TITLE
公式中的标点不是应该用中文的吗？

### ISSUE THREAD

**Issue by indam** [exacity/deeplearningbook-chinese#63]
一点小问题~
既然翻译为中文版，公式中的标点就应该使用中文标点，因为公式也是句子的一部分。不然就像“马上，我在路上了,一会儿就到。”一样。

提供一个不太高明的tex解决方法：
`\newcommand{\mjh}{~\text{。}}`
`\newcommand{\mdh}{~\text{，}}`
`\newcommand{\mfh}{~\text{；}}`

用法如下：
`\begin{equation}`
`E = \sqrt{m^2+p^2} \mdh`
`\end{equation}`

具体请参考：[http://www.cjstp.cn/cjstp/ch/reader/create_pdf.aspx?file_no=20070150&flag=1&journal_id=cjstp](http://www.cjstp.cn/cjstp/ch/reader/create_pdf.aspx?file_no=20070150&flag=1&journal_id=cjstp)

**Comment by kkpoker** [comment]
科技文献用英文标点很正常？或许(

**Comment by SwordYork** [comment]
@indam Hello，我们试过，很难看，所以放弃了，保留英文。

**Comment by indam** [comment]
@SwordYork 好的，多谢回复。
不过我觉得挺正常的啊。
![2017-04-16_180251](https://cloud.githubusercontent.com/assets/1610302/25070382/043d73e8-22cf-11e7-8847-3985a5c5193b.jpg)

OK, whatever, 多谢翻译。
