### ISSUE TITLE
逗号句号全角半角混用有点难过

### ISSUE THREAD

**Issue by XuLYC** [exacity/deeplearningbook-chinese#64]
真的不是故意找茬。。。。。
一般偏理工科的书都会通篇用半角逗号句号吧，这样和公式们在一起看起来舒服一点。

**Comment by SwordYork** [comment]
@XuLYC hello，多谢建议，见#63 。我认为公式在英文的上下文内，所以使用英文标点。

**Comment by XuLYC** [comment]
是行内公式被全角符号了。。。可以看下周志华老师的机器学习，习惯是偏向通篇半角符号的，混排的会比较少见。

**Comment by SwordYork** [comment]
@XuLYC 恩，那个我再考虑一下，因为行内公式我们就认为是中文的上下文了。

**Comment by SwordYork** [comment]
我们决定暂时先保持原样，之后再作考虑，谢谢！
