### ISSUE TITLE
第八章：“高斯值”是什么意思

### ISSUE THREAD

**Issue by ninesunqian** [exacity/deeplearningbook-chinese#65]
”稀疏初始化有助于实现单元之间在初始化时更具多样性。 但是，它也非常偏好于具有很大高斯值的权重。“ 一句中“高斯值”不太规范，google也查不到这个词。 是否是小方差的高斯分布的意思？

**Comment by liber145** [comment]
谢谢指出。原文这块的句子是 "However, it also imposes a very strong prior on the weights that are chosen to have large Gaussian values." 所以给直接翻译成 高斯值 了。
这里出现“高斯”，是指前面提到的 uniform 和 gaussian 两种初始化方法。网络层输入节点数 m 和输出节点数 n 太大时，书中的这两种方法会使得权重值很小。因此有人提出稀疏初始化，只让部分权重非零。这样又会偏向于数值较大的权重（这里的gaussian value应该只是想说用gaussian来初始化吧）。继而解释如果一个不正确的权重初始化很大，要很久才能矫正。
感觉翻译成“它也非常偏好于具有较大数值的权重”，更好理解，你看如何。

**Comment by SwordYork** [comment]
感觉得想个能保留高斯的翻译。

**Comment by ninesunqian** [comment]
个人认为，翻译成“它也非常偏好于具有较大数值的权重” 使上下文更顺畅。

**Comment by SwordYork** [comment]
“它也非常偏好于具有较大数值的权重” 这个翻译不符合原文，不能为了顺畅丢了原意。
原文意思是 利用稀疏初始化，会给那些被选择的权重强加非常强的先验，即具有大的高斯值。
这个我不确定，我不知道Gaussian value什么意思。
直接保留。

**Comment by SwordYork** [comment]
@ninesunqian @liber145 可能断句不对啊，
However, it also imposes a very strong prior on the weights to have large Gaussian values.
 that are chosen 修饰 the weights，不能丢了这个修饰。

**Comment by liber145** [comment]
下面的断句更正常一些吧
However, it also imposes a very strong prior on (the weights that are chosen to have large Gaussian values).

**Comment by ninesunqian** [comment]
可以联系一下作者，确认一下“Guassian value” 到底是什么意思。

**Comment by ninesunqian** [comment]
根据译文8.7.1， 272页，“hl-1 仍然保持着单位高斯”， “高斯值”应该就是方差或标准差。

**Comment by sailordiary** [comment]
同意@liber145，Gaussian value即value of the Gaussian，指权重θ按高斯分布的取值p(θ)。
前面说了，"We can think of initializing the parameters θ to θ0 as being similar to imposing a Gaussian prior p(θ) with mean θ0. "(p303, +6)，权值是按高斯分布初始化的。所以这里我觉得可以翻译成“获得较大取值的权重也同时被加了很强的高斯先验”。

**Comment by SwordYork** [comment]
@sailordiary @liber145 我更觉得是`are chosen to` 是指前面的稀疏初始化选择（注意那个However）的那些权重（即初始化非零的权重），这些被选择的非零权重被加了很强的高斯先验，而没被选择的零权重则没有先验。因此错误的大值需要花费很长时间来通过梯度下降修正。这里在解释稀疏初始化。

> Sparse initialization helps to achieve more diversity among the units at initialization time. However, it also imposes a very strong prior on the weights that are chosen to have large Gaussian values. Because it takes a long time for gradient descent to shrink “incorrect” large values, this initialization scheme can cause problems for units such as maxout units that have several filters that must be carefully coordinated with each other.

**Comment by liber145** [comment]
这样的话，这句话的断句变成了 "However, it also imposes a very strong prior on (the weights that are chosen) to have large Gaussian values."，那么写成 "However, it also imposes a very strong prior on the chosen weights to have large Gaussian values." 更合适些。 
稀疏选择的权重并不一定都很大，进行高斯初始化后，有些权重大，有些权重小。然后，错误的大值具有很强的先验，需要花费很长时间来通过梯度下降修正。 
@sailordiary 给的翻译更顺畅些，去掉里面的“高斯”，保留成“获得较大取值的权重也同时被加了很强的先验”，怎么样。

**Comment by liber145** [comment]
@ninesunqian 确实可以联系下作者，稍后我们邮件问下。不过可能不会回。。。。。
