### ISSUE TITLE
第6.5.9节J对zi的导数，原书qi-pi正确，中文版错误

### ISSUE THREAD

**Issue by JiaqiYao** [exacity/deeplearningbook-chinese#66]
![6 5 9](https://cloud.githubusercontent.com/assets/24631903/25268172/49999276-26aa-11e7-8c31-25ef7dd6a216.PNG)

**Comment by KevinLee1110** [comment]
非常感谢！！你是对的，我在推导时遗漏了`q_j`中也会有`z_i`的项，所以原作者是对的。感谢你的详细推导！！
