### ISSUE TITLE
8.6.3中存储受限的BFGS一段：有“但起始假设是M(t-1) 是单位矩阵。”  起始矩阵是否离当前矩阵太近了？

### ISSUE THREAD

**Issue by ninesunqian** [exacity/deeplearningbook-chinese#69]
起始矩阵是否离当前矩阵太近了？
如果使用最近的m步计算， 起始矩阵应该是M(t-m)
参见：http://www.hankcs.com/ml/l-bfgs.html

**Comment by liber145** [comment]
额，这个取决于如何理解M^(t-1)吧。
书中该处前后没有M^(t-1)，也没说M^(t-1)就表示L-BFGS只保存最近的一个。我觉得最好写成前面出现过的M_t，表示是在第t步迭代中。
暂时还是按书中来翻译了。

**Comment by ninesunqian** [comment]
OK，你们决定吧。
