### ISSUE TITLE
regularization “正规”与“正则”翻译问题

### ISSUE THREAD

**Issue by freedomRen** [exacity/deeplearningbook-chinese#70]
regularization 这个词在机器学习领域有如下翻译
1 正规化  
2 正则化
在周志华机器学习中翻译成正则化，但是这里的正则容易和正则表达式的正则的意思相冲突或者误解，cnki的词典中，这个单词建议翻译成“正规化”，所以建议使用正规化代替目前翻译的正则化

**Comment by sailordiary** [comment]
一般还是说正则化的比较多吧。而且感觉好像没有什么误解的问题，很多词本身就有好几个翻译，比如normalization。

P.S. 其实regular，canonical，normal，standard几个词很多时候意思都差不多。。从数学角度回想了一下，中文里一般regular译正则（regularization正则化，regular language正则语言，regular solution正则解），normal译正规（normal equation正规方程，normal subgroup正规子群，normalization正规化/规范化/标准化），canonical译典范或标准（canonical map典范映射，canonical form标准形/典范形），standard译标准（standard basis标准基）。

**Comment by freedomRen** [comment]
谢谢！

**Comment by SwordYork** [comment]
非常感谢两位！@sailordiary 总结的很有道理！
