### ISSUE TITLE
深度前馈神经网络能够避免梯度爆炸或者消失部分的翻译问题

### ISSUE THREAD

**Issue by freedomRen** [exacity/deeplearningbook-chinese#71]
8.2.5 倒数第二段
原文：Recurrent networks use the same matrix W at each time step, but feedforward networks do not, so even very deep feedforward networks can largely avoid the vanishing and exploding gradient problem (Sussillo, 2014)
目前翻译文章：循环网络各时间步上使用相同的矩阵W，而前馈网络没有。因而即使是非常深层的前馈网络也能一定程度上避免梯度消失于爆炸问题(Sussillo, 2014)。
找了下引文地址：https://arxiv.org/abs/1412.6558 题目是：Random Walk Initialization for Training Very Deep Feedforward Networks
问题：这里“因而即使是非常深层的前馈网络也能一定程度上避免梯度消失于爆炸问题”，虽然看似很贴合原文的语序，但是容易造成误解，因为在很多教程上讲解“为什么深度神经网络难以训练”的问题的时候会引出梯度消失和爆炸问题，所以这里原文的意思是指“所以即使（使用）非常深层的前馈网络，（但是这也）能很大程度上（有效地）避免梯度消失和爆炸问题”，这样断开翻译比较容易将文章表达的转折意思表达清楚，原来的翻译我还是比较费劲的去找转折意思的转折点。
谢谢！

**Comment by liber145** [comment]
嗯，你翻译得更贴切！多谢啊！
