### ISSUE TITLE
第9章  9.10节，讲gabor函数的图9.18  中三幅图片的顺序错了

### ISSUE THREAD

**Issue by ninesunqian** [exacity/deeplearningbook-chinese#72]
如题。与英文的不符。

**Comment by KevinLee1110** [comment]
感谢你的提醒~我们翻译用的版本和[公开的版本](http://www.deeplearningbook.org/contents/convnets.html)不太一样，可能是原作者们后来进行了微调。为了和原版印刷书籍保持一致，我们还是采用我们拿到的翻译版本。

**Comment by KevinLee1110** [comment]
嗯嗯，你是对的！我们先前拿到的翻译版本图片顺序确实错了，[公开的版本](http://www.deeplearningbook.org/contents/convnets.html)没有问题。
