### ISSUE TITLE
9.8节中，“卷积等效于使用傅立叶变换将输入与核都转换到频域、执行两个信号的逐点相乘，再使用傅立叶逆变换转换回时域。 对于某些问题的规模，这种算法可能比离散卷积的朴素实现更快。” 怎么理解？

### ISSUE THREAD

**Issue by ninesunqian** [exacity/deeplearningbook-chinese#73]
这句话怎么理解？ 能否给个例子。比如：输入转化到频域是：I1, I2, I3,  核转化到频域是 w1, w2, 逐点相乘是否是： I1*w1,  I1*w2,  I1*w3,  I2*w1,  I2*w2,  I2*w3,  I3*w1,  I3*w2, I3*w3,  然后这6个频点再转换到时域？

**Comment by KevinLee1110** [comment]
并不是这样，你这样向量的维度不一致就不叫逐点相乘了。离散的傅里叶变换我没看过(我那时有专门一门课叫DSP)，只能用本科时学的有限的信号与系统的知识来回答你了。在我看来，核在时域上可以理解为一个时间窗函数(参考[这里](https://en.wikipedia.org/wiki/Fourier_transform)的[Rectangular function](https://en.wikipedia.org/wiki/File:Rectangular_function.svg))，它变换到频域后类似[这张图](https://en.wikipedia.org/wiki/Fourier_transform#/media/File:Sinc_function_(normalized).svg)，横坐标是`$\omega$`。而输入变换到频域上也是横跨整个频率轴。时域上的卷积等效于频域上的相乘，所以频域上每个点逐点相乘是没问题的。之后再将乘得的函数使用傅里叶逆变换变换回时域就得到结果了。离散的傅里叶变换可能公式有点区别，但是总体思想是一样的。
