### ISSUE TITLE
9.8中：“当一个d维的核可以表示成d个向量（每一维一个向量）的外积时，该核被称为可分离的” 怎么理解

### ISSUE THREAD

**Issue by ninesunqian** [exacity/deeplearningbook-chinese#74]
按照后面的解释，可以理解为d维向量中的各个分量是独立的，互不影响。 但如何核转化为d个向量的外积？ 此处“外积”是否为矩阵的“叉乘”？

**Comment by KevinLee1110** [comment]
关于Outer product请参考[wiki](https://en.wikipedia.org/wiki/Outer_product)中的Tensor multiplication一节。我只听说过向量的叉乘，没太听说过矩阵的叉乘(参考叉乘的[wiki](https://en.wikipedia.org/wiki/Cross_product))。核能否分离，以及具体的分离算法我没有做过研究，2维情况请参考[这篇文章](http://blogs.mathworks.com/steve/2006/10/04/separable-convolution/)。

**Comment by KevinLee1110** [comment]
因为我们要整合一下现在的版本，先把issue关了。如果还有其他问题，欢迎继续提issue。
