### ISSUE TITLE
Chapter 1 前言 关于名为 Fred 的人在早上剃须的故事

### ISSUE THREAD

**Issue by Sofring** [exacity/deeplearningbook-chinese#75]
“它的推理引擎检测到故事中的不一致性:它知道人没有电气零件”这句话中“它知道人没有电气零件”首次阅读有歧义，我对比英文才能理解。
提个建议哈 people也有人类的意思 是否改成这样“它知道人类的构成不包含电器零件”？

**Comment by wenlei** [comment]
从理解上，不如用人体。人体不由电器构成。

:D
Wenlei

**Comment by SwordYork** [comment]
很有道理，多谢！我会改一下。

**Comment by SwordYork** [comment]
已更正，多谢！
