### ISSUE TITLE
10.2.4中，图10.10“允许RNN对给定x的序列后，相同长度的y序列上的任意分布建模”，而图10.3"仅能表示给定x后，y值彼此条件独立的分布"。这句话怎么理解？

### ISSUE THREAD

**Issue by ninesunqian** [exacity/deeplearningbook-chinese#81]
有三个问题我不是很明确，请多指教。
1 “条件分布”中的条件是指x序列吗？
2 根据图模型分析时，这句话中的“y”值，在图的是指y(t-1), y(t).... 还是o(t-1), o(t)...
3 如何得出的y值是否条件独立。是根据这个方法吗？ http://blog.csdn.net/u011467621/article/details/47971895

谢谢！

**Comment by SwordYork** [comment]
1. 是条件于x，见10.35
2. 我不是很清楚问题是什么，找了半天没找到。
3. y值条件独立是根据实际情况来的，实际情况决定y值是否相互条件独立。你给的网址是判断y值是否条件独立的方式。当然你可以假设是条件独立的，这样可能导致建模效果不好。
