### ISSUE TITLE
关于参考文献的问题

### ISSUE THREAD

**Issue by pkuwwt** [exacity/deeplearningbook-chinese#90]
出于个人学习的需要，我自己把图片和参考文献给加上了。在校对过程中，发现至少有20多处参考文献和原著没有对应上，即本来是两篇参考文献，但译著中却显示为相同。不知道书籍出版了没有，这些问题有可能对认真阅读的读者带来困扰。

我将原著与译著之间的参考文献对应上，然后发现了如下出问题的映射。这些都是译著一个文献对应原著多个文献的情况。

ElHihi+Bengio-nips8 -> Hihi and Bengio 1996;Hihi and Bengio 1996;El Hihi and Bengio 1996;Hihi and Bengio 1996
Glorot+al-AI-2011-small -> Glorot et al. 2011a;Glorot et al. 2011a;Glorot et al. 2011a;Glorot et al. 2011a;Glorot et al. 2011a;Glorot and Bengio 2010
Goodfellow-et-al-NIPS2014-small -> Goodfellow et al. 2014c;Goodfellow et al. 2014c;Kingma and Welling 2014a;Goodfellow et al. 2014c;Goodfellow et al. 2014c
WardeFarley+al-ICLR2014 -> WardeFarley et al. 2014;Warde-Farley et al. 2014;WardeFarley et al. 2014
Szegedy-et-al-arxiv2014 -> Szegedy et al. 2014a;Szegedy et al. 2014a;Szegedy et al. 2014a;Szegedy et al. 2014a;Szegedy et al. 2014a;Szegedy et al. 2014b;Szegedy et al. 2014a;Szegedy et al. 2014a
Larochelle2008 -> Larochelle and Bengio 2008;Larochelle et al. 2008
Kingma+Welling-ICLR2014 -> Kingma 2013;Kingma and Welling 2014a;Goodfellow et al. 2014c
Graves-et-al-arxiv2014 -> Graves et al. 2014a;Graves et al. 2014b;Graves et al. 2014b
Bengio+Monperrus-2005 -> Bengio and Monperrus 2005;Bengio et al. 2006c;Bengio and Monperrus 2005
Rumelhart86 -> Rumelhart et al. 1986c;Rumelhart et al. 1986b
Hinton-et-al-arxiv2012 -> Hinton et al. 2012a;Hinton et al. 2012c;Hinton et al. 2012c;Hinton et al. 2012c
Hinton-et-al-2012 -> Hinton et al. 2012b;Hinton et al. 2012a
bengio2013estimating -> Bengio 2013;Bengio et al. 2013b;Bengio et al. 2013b
Russakovsky2014imagenet -> Russakovsky et al. 2014a;Russakovsky et al. 2014b
Mnih2013 -> Mnih et al. 2013;Mnih and Kavukcuoglu 2013;Mnih and Kavukcuoglu 2013
Graves-et-al-ICASSP2013 -> Graves et al. 2013;Graves et al. 2013;Graves et al. 2013;Graves et al. 2013;Graves 2013;Graves et al. 2013;Graves et al. 2013;Graves 2013;Graves 2013;Graves et al. 2013;Graves et al. 2013
Bengio91z -> Bengio et al. 1991;Bengio 1991;Bengio et al. 1991
Rumelhart86c -> Rumelhart et al. 1986b;Rumelhart et al. 1986a;Rumelhart et al. 1986b
Hinton06 -> Hinton et al. 2006;Hinton et al. 2006;Hinton et al. 2006;Hinton 2006;Hinton et al. 2006;Hinton et al. 2006;Hinton et al. 2006
Montufar-et-al-NIPS2014 -> Montufar et al. 2014;Montufar et al. 2014;Montufar et al. 2014;Montufar et al. 2014;Montufar et al. 2014;Montúfar 2014
Graves+Schmidhuber-2009 -> Graves and Schmidhuber 2009;Graves et al. 2009

**Comment by SwordYork** [comment]
@pkuwwt 收到，请问有没有详细的位置?
@exacity/translation 我们核对一下。

**Comment by pkuwwt** [comment]
我回头再整理一下

**Comment by pkuwwt** [comment]
10.9.1
Bengio91z在其它地方对应于Bengio et. al 1991，但此处原文是Bengio 1991

**Comment by pkuwwt** [comment]
10.10.1
手写识别\citep{Graves-et-al-ICASSP2013} 处原文是Graves, 2013，因此很可能是Graves-arxiv2013。

而且原文Handwritting generation应该翻译成手写生成吧？

10章结尾处的Graves-et-al-ICASSP2013也对应于原文的Graves, 2013

**Comment by pkuwwt** [comment]
10章另一处10.11.2
还有学者提出\citep{Graves-et-al-ICASSP2013} 处原文是Graves, 2013

**Comment by pkuwwt** [comment]
第5章5.1.3
\cite{Mnih2013}介绍了...
原文是Mnih et al, 2013

这个参考文献你们估计漏掉了

**Comment by pkuwwt** [comment]
12章12.1.5
Bengio2013estimating和bengio-arxiv13-condcomp都是指Estimating  or propagating gradients through stochastic neurons for conditional computations吧

这里的Bengio2013estimating原文是Bengio, 2013，即文献Deep learning of representation

**Comment by pkuwwt** [comment]
第1章1.2.4
Hinton-et-al-arxiv2012}使得语音识别

这里肯定搞错了，因为译文中多处Hinton-et-al-arxiv2012指向了2012c

**Comment by pkuwwt** [comment]
第5章5.11.2
非局部的泛化\citep{}，两个文献写成一样了，第二个应该是Bengio2006c

**Comment by pkuwwt** [comment]
19章结尾

Kingma-arxiv2013写成了Kingma+Welling-ICLR2014

**Comment by pkuwwt** [comment]
7章7.6
更好的权衡\citep{} 第二个文献应该是Larochelle+Bengio-2008或Larochelle+Bengio-2008-small

**Comment by pkuwwt** [comment]
7章7.14
\gls{adversarial_training}\citep{Szegedy-et-al-arxiv2014

应该是Szegedy-ICLR2014

**Comment by pkuwwt** [comment]
8章8.4
\cite{Glorot+al-AI-2011-small}建议使用

原文是Glorot and Bengio 2010，这个文献大概也漏掉了

**Comment by pkuwwt** [comment]
暂时确认了的就是这么多了

**Comment by SwordYork** [comment]
@pkuwwt 非常感谢，不一定来得及改。我们尽快确认。

**Comment by SwordYork** [comment]
我自己也检查了一遍，发现你的PDF可能有点滞后，有些问题已经修复。不过大部分你提的问题都是存在的，非常感谢！但纸质版不一定能赶上。

**Comment by snowjade** [comment]
@pkuwwt  偷偷问一下，你加的图片来源是哪里啊？ 难道是从有图片的PDF里截图么？
