### ISSUE TITLE
第五章 117页翻译的问题

### ISSUE THREAD

**Issue by tjliupeng** [exacity/deeplearningbook-chinese#92]
等式5.66前面的一句话："对比于均方误差的对数似然"

原文是Comparing the log-likelihood with the mean squared error，应该翻译成"对比均方误差和对数似然"。

谢谢

**Comment by SwordYork** [comment]
显然我们错了，多谢！ @liber145

**Comment by liber145** [comment]
嗯，多谢指正啊！
