### ISSUE TITLE
第五章 121页的翻译

### ISSUE THREAD

**Issue by tjliupeng** [exacity/deeplearningbook-chinese#93]
等式5.78后面的一句话: 所有不包括的参数向量w的项都已经被删去了；它们意味着分布的积分必须归一这个事实。原文是All terms that do not include the parameter vector w have been omitted; they are implied by the fact that the distribution must be normalized to integrate to 1. 

“they are implied by”是被动语态，个人觉得应该是“分布的积分必须归一这个事实意味着要删去所有不包括的参数向量w的项”，虽然不明白是为什么。

**Comment by SwordYork** [comment]
@liber145 有偏差。。你来改改。

**Comment by liber145** [comment]
@tjliupeng @SwordYork  嗯，有道理。你翻得挺好的。书中是觉得exp形式对应高斯分布，去掉5.77中的第二项后，5.78就变成了5.73那样的高斯形式，保证归一。其实我觉得理解成5.77中第二项和w无关就可以了。
