### ISSUE TITLE
第三章 3.13信息论 错别字

### ISSUE THREAD

**Issue by codeVerySlow** [exacity/deeplearningbook-chinese#94]
信息论是应用数学的一个分支，主要研究的是对一个信号包含信息的多少进行量化。 它最初被发明是用来研究在一个含有噪声的信道上用离散的字母表来发送消息，例如通过无线电传输来通信。 在这种情况下，信息论告诉我们如何设计最优编码，以及计算从一个特定的概率分布上采样得到、使用多种不同编码机制的消息的期望长度。 在机器学习中，我们也可以把信息论应用在连续型变量上，而信息论中一些消息长度的解释不怎么使用

最后这个使用应该是适用

**Comment by SwordYork** [comment]
@KevinLee1110 感觉一下。

**Comment by KevinLee1110** [comment]
@codeVerySlow 先前在外地，抱歉回复晚了。非常感谢你的提醒。原文是
> In the context of machine learning, we can also apply information theory to continuous variables where some of these message length interpretations do not apply.

现在更正如下
> 在机器学习中，我们也可以把信息论应用于某些消息长度解释不适用情况下的连续型变量。
