### ISSUE TITLE
第六章 6.2基于梯度的学习 笔误

### ISSUE THREAD

**Issue by duzeyan** [exacity/deeplearningbook-chinese#95]
本节第十二行，”这种用于训练前馈神经网络以及几乎所有深度模型的迭代的基于梯度的优化算法会在**第第八章**详细介绍“

**Comment by pkuwwt** [comment]
**第八章**是程序生成，怎么会错？你的pdf浏览器出问题了吧

**Comment by SwordYork** [comment]
@duzeyan @pkuwwt 由于我们之前未定义chapter，后来才改，导致出现两个“第”。多谢！

**Comment by SwordYork** [comment]
@duzeyan 现在源码是没有问题的，你的PDF可能要更新。
