### ISSUE TITLE
生成的书签里,参考文献和术语在第三部分里面

### ISSUE THREAD

**Issue by wuqi** [exacity/deeplearningbook-chinese#98]
生成的书签里,参考文献和术语位置不对,在第三部分里面

**Comment by SwordYork** [comment]
很有道理，但我不知道怎么处理。

**Comment by wuqi** [comment]
我也不知道,不熟悉latex..  不过不知道这样行不行,看起来是类似的问题  https://tex.stackexchange.com/questions/131959/pdf-bookmarks-for-references-and-index-appear-as-contained-in-the-appendix-wron

**Comment by SwordYork** [comment]
@wuqi 确实可以，不过pdf暂时不更新。。你可以自行编译。
