### ISSUE TITLE
7.12节翻译错误

### ISSUE THREAD

**Issue by yzmyyff** [exacity/deeplearningbook-chinese#99]
Recall that to learn with... 这一段, 中文里面有一句是"我们会使用基于小批量的学习算法和较小的步长, 如**梯度下降**等."
实际上应该是随机梯度下降.

**Comment by SwordYork** [comment]
你好，你的PDF可能需要更新。latex没有问题。

**Comment by yzmyyff** [comment]
对, 我直接从项目主页上下载的, 这个PDF是多久更新一次?

2017-06-15 9:40 GMT+08:00 Nouce <notifications@github.com>:

**Comment by SwordYork** [comment]
@yzmyyff 现在不更新了，只更新latex代码。。。那个PDF算最后了，纸质版之后可能会更新一下。

**Comment by yzmyyff** [comment]
这样, 多谢了

2017-06-15 9:53 GMT+08:00 Nouce <notifications@github.com>:
